apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-external
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: openflow
    port: 6653
    nodePort: 31633
  - name: ovsdb
    port: 6640
  - name: east-west
    port: 9876
  - name: cli
    port: 8101
  - name: ui
    port: 8181
    nodePort: 31818
  selector:
    app: {{ template "fullname" . }}